- name: download kibana
  shell: bash -lc "wget https://download.elastic.co/kibana/kibana/kibana-4.1.1-linux-x64.tar.gz"
  tags:
    - kibana
    - elastic

- name: install kibana
  shell: bash -lc "tar zxvf kibana-4.1.1-linux-x64.tar.gz; mv kibana-4.1.1-linux-x64 /usr/local/"
  ignore_errors: true
  tags:
    - kibana
    - elastic

- name: link kibana
  file: >
    path=/usr/local/kibana
    src=/usr/local/kibana-4.1.1-linux-x64
    state=link
  tags:
    - kibana
    - elastic

- name: Change acceptable tcp port for kibana on iptables
  lineinfile:
    dest: "/etc/iptables/{{ item }}"
    state: present
    regexp: "^#-A INPUT -m state --state NEW -m tcp -p tcp --dport 5601 -j ACCEPT"
    line: "-A INPUT -m state --state NEW -m tcp -p tcp --dport 5601 -j ACCEPT"
    backrefs: yes
    backup: yes
  with_items:
    - 'rules.v4'
    - 'rules.v6'
  notify:
    - restart iptables
  tags:
    - kibana
    - iptables

#- name: kibana service state
#  shell: bash -lc "cd /usr/local/kibana; ./bin/kibana > ./kibana.log &"
#  tags:
#    - kibana
#    - elastic
