---
- hosts: all
  sudo: yes
  roles:
    - common
    - ruby-rbenv
  tags:
    - task-common

- hosts: web
  sudo: yes
  roles:
    - mysql-server
    - passenger
    - user-deploy
  tags:
    - task-web

- hosts: fluentd
  sudo: yes
  roles:
    - fluentd
  tags:
    - task-fluentd

