---
- name: import epel key
  command: /bin/rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6

- name: restart sshd
  service: name=sshd state=restarted

- name: restart iptables
  service: name=iptables state=restarted
  with_items:
    - iptables
    - ip6tables
